version: '3.8'

services:
  playwright:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: playwright-tests
    volumes:
      - .:/app/  # Persistir resultados de pruebas
    environment:
      - HEADLESS=true
      - CI=true
      # - NODE_OPTIONS=--max-old-space-size=8192  # <-- Añade esta línea
    # Para depuración con VNC (opcional):
    # ports:
    #   - "5900:5900"  # VNC
    #   - "6090:6090"  # noVNC web
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:6090"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
    # restart: "no"
    command: ["yarn", "test:u"]
    deploy:  # Solo para Docker >= 19.03
      resources:
        limits:
          memory: 8G  # 8GB para el contenedor